modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC BY-NC-SA 4.0"
issueTrackerURL = "https://github.com/st0x0ef/Stellaris/issues"
[[mods]]
modId = "stellaris"
version = "${version}"
displayName = "Stellaris"
logoFile = "logo.png"
description = '''
Fly into new world!
'''
[[dependencies.stellaris]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.stellaris]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.stellaris]]
modId = "architectury"
type = "required"
versionRange = "[11,)"
ordering = "NONE"
side = "BOTH"
